name: whizrock-premier-staging
region: syd

services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: yourusername/whizrock-premier

    build_command: npm run build
    run_command: npm start

    environment_slug: node-js

    http_port: 3000

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: NODE_ENV
        value: production

      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${NEXT_PUBLIC_SUPABASE_URL}
        type: SECRET

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        type: SECRET

      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        type: SECRET

      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}

      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
        type: SECRET
        scope: RUN_TIME

      - key: GHL_API_KEY
        value: ${GHL_API_KEY}
        type: SECRET
        scope: RUN_TIME

      - key: GHL_LOCATION_ID
        value: ${GHL_LOCATION_ID}
        type: SECRET
        scope: RUN_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
